version: '3.8'

services:
  qa_app:
    build: .
    ports:
      - "8009:8009"
    environment:
      - DATABASE_URL=postgresql://postgres:password@qa_db:5432/qa_db
      - REDIS_URL=redis://qa_redis:6379/9
      - AUTH_SERVICE_URL=http://auth_app:8000
      - CRM_SERVICE_URL=http://crm_app:8001
      - BOOKING_SERVICE_URL=http://booking_app:8002
      - TOUR_SERVICE_URL=http://tour_app:8003
      - FLEET_SERVICE_URL=http://fleet_app:8004
      - HR_SERVICE_URL=http://hr_app:8005
      - FINANCIAL_SERVICE_URL=http://financial_app:8006
      - NOTIFICATION_SERVICE_URL=http://notification_app:8007
      - SECRET_KEY=super-secret-key-change-this
      - ENVIRONMENT=development
    depends_on:
      - qa_db
      - qa_redis
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    command: uvicorn qa_service.main:app --host 0.0.0.0 --port 8009 --reload

  qa_db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=qa_db
    ports:
      - "5441:5432"
    volumes:
      - qa_postgres_data:/var/lib/postgresql/data

  qa_redis:
    image: redis:7-alpine
    ports:
      - "6388:6379"
    volumes:
      - qa_redis_data:/data

volumes:
  qa_postgres_data:
  qa_redis_data: